name: App build
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

env:
  dfx_version: 0.20.0

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: ZenVoich/setup-mops@v1
      - uses: dfinity/setup-dfx@main

      - name: Confirm dfx installation
        run: dfx --version

      - name: make sure moc is installed
        run: mops toolchain bin moc || mops toolchain use moc latest

      - name: Build canisters and prepare tests
        run: |
          npm i
          dfx generate

      - name: Run tests
        run: |
          npm run test
